// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSOPKy_b9MM7WwlKyZ0HVsFYnRuMBft7E',
    appId: '1:115811546693:web:521a69b3b149514a0d552c',
    messagingSenderId: '115811546693',
    projectId: 'simarku-2f254',
    authDomain: 'simarku-2f254.firebaseapp.com',
    storageBucket: 'simarku-2f254.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-v4tIZFJE2qqjEPXkEJvOgwX-W15lFn8',
    appId: '1:115811546693:android:804a22816eb698c60d552c',
    messagingSenderId: '115811546693',
    projectId: 'simarku-2f254',
    storageBucket: 'simarku-2f254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxHOpNgHBR4dbmhJp1HJ4n2dhUUGBPZk',
    appId: '1:115811546693:ios:36c50b09a7da27c50d552c',
    messagingSenderId: '115811546693',
    projectId: 'simarku-2f254',
    storageBucket: 'simarku-2f254.appspot.com',
    iosBundleId: 'com.example.simarku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxHOpNgHBR4dbmhJp1HJ4n2dhUUGBPZk',
    appId: '1:115811546693:ios:e2b190d00c6bf9ad0d552c',
    messagingSenderId: '115811546693',
    projectId: 'simarku-2f254',
    storageBucket: 'simarku-2f254.appspot.com',
    iosBundleId: 'com.example.simarku.RunnerTests',
  );
}
